### ISSUE TITLE
`math.round` does not exist

### ISSUE THREAD

**Issue by Bituvo** [fluxionary/minetest-futil#1]
Your latest commit, "boxes", broke the mod.
https://github.com/fluxionary/minetest-futil/blob/main/minetest/player.lua#L138

I suggest adding this function:
```lua
function math.round(num)
    return math.floor(num + 0.5)
end
```

**Comment by appgurueu** [comment]
[This function should already be provided by Minetest.](https://github.com/minetest/minetest/blob/3e148e2810a2b1bb47cada2bd431df8f0bad2f96/doc/lua_api.txt#L3624)

I suggest not going with the suggestion: Mods should not mess with the global environment (apart from adding their mod API table to it). Your suggested fix would override the Minetest-provided function, changing the semantics. [For reference, here is the source of the Minetest-provided function](https://github.com/minetest/minetest/blob/3e148e2810a2b1bb47cada2bd431df8f0bad2f96/builtin/common/misc_helpers.lua#LL244-L249C4):

```lua
function math.round(x)
	if x >= 0 then
		return math.floor(x + 0.5)
	end
	return math.ceil(x - 0.5)
end
```

**Comment by Bituvo** [comment]
Do you have any idea as to why my world wouldn't recognize this command?

**Comment by BuckarooBanzay** [comment]
fyi: the `math.round` function doesn't seem to exist in the multicraft fork: https://github.com/MultiCraft/MultiCraft/blob/main/builtin/common/misc_helpers.lua

**Comment by Bituvo** [comment]
That makes sense. My server runs on Multicraft. I think that the canonical rounding function should be redefined in player.lua

**Comment by appgurueu** [comment]
No. This is a mod for *Minetest*. Raise an issue on the MultiCraft repo. They should get their act together. And `player.lua` definitely would be the wrong place for such a (re)definition. `futil` *could* bring its own rounding utility to appease MuC, but it definitely doesn't have to.

**Comment by Bituvo** [comment]
I'll go ahead and create an issue there, but I don't think anybody is going to see it.
Edit: https://github.com/MultiCraft/MultiCraft/issues/126

**Comment by fluxionary** [comment]
somehow just noticed this today (i'm behind on my emails). i definitely agree w/ the sentiment that mods shouldn't alter the global namespace.
