### ISSUE TITLE
fake_inventory.room_for_all could fail to find space

### ISSUE THREAD

**Issue by SwissalpS** [fluxionary/minetest-futil#2]
I have not run any test, just read the code and noticed this scenario:
(I have used simplified item names)

destination list: { "", "", "cobble 12", "cobble 12" }  
items to add: { "cobble 99", "cobble 6", "wood 4" }

from reading the code the resulting list would be full before wood ist tried and would return false even though there would be space.

{ "cobble 99", "cobble 6", "cobble 12", "cobble 12" } returning "wood 4"

Here is how I'm going to offer to fix https://github.com/mt-mods/pipeworks/issues/61:
https://github.com/SwissalpS/minetest_pipeworks/blob/802c1e73c6670cc5631838733c98b125aa849698/autocrafter.lua#L35

**Comment by fluxionary** [comment]
good catch. i'm pretty sure FakeInv departs from how `InvRef.add_item` works in this case, and i'll work to resolve that soon.

**Comment by fluxionary** [comment]
should be fixed in https://github.com/fluxionary/minetest-futil/commit/d7c1730d6840b33d034a2ce87d1d9a1538370d0d

**Comment by SwissalpS** [comment]
yep, looks better now :D
